
import __ASTRO_IMAGE_IMPORT_1xPh4x from "./_images/northwind-16x9.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Felevate-salon.md";
import __ASTRO_IMAGE_IMPORT_1ubQea from "./_images/northwind-16x9.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Foceanview-therapy.md";
import __ASTRO_IMAGE_IMPORT_Z1d0vaS from "./_images/northwind-16x9.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fspeech-for-yourself.md";
import __ASTRO_IMAGE_IMPORT_MMbri from "./_images/northwind-4x5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Felevate-salon.md";
import __ASTRO_IMAGE_IMPORT_Z1nOAjo from "./_images/northwind-4x5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Foceanview-therapy.md";
import __ASTRO_IMAGE_IMPORT_2dOo6F from "./_images/northwind-4x5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fspeech-for-yourself.md";
import __ASTRO_IMAGE_IMPORT_Z1DgQ04 from "./_images/post-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwhy-astro-for-agency-sites.mdx";
import __ASTRO_IMAGE_IMPORT_jvWQA from "./_images/post-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fdesigning-for-slow-connections.mdx";
import __ASTRO_IMAGE_IMPORT_Z1YgYCL from "./_images/post-3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fseo-audits-we-actually-run.mdx";
import __ASTRO_IMAGE_IMPORT_1rTpJ6 from "./_images/post-4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Frunning-discovery-workshops.mdx";
import __ASTRO_IMAGE_IMPORT_1WFRv7 from "./_images/post-5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpricing-a-small-agency.mdx";
export default new Map([["./_images/northwind-16x9.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Felevate-salon.md", __ASTRO_IMAGE_IMPORT_1xPh4x], ["./_images/northwind-16x9.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Foceanview-therapy.md", __ASTRO_IMAGE_IMPORT_1ubQea], ["./_images/northwind-16x9.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fspeech-for-yourself.md", __ASTRO_IMAGE_IMPORT_Z1d0vaS], ["./_images/northwind-4x5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Felevate-salon.md", __ASTRO_IMAGE_IMPORT_MMbri], ["./_images/northwind-4x5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Foceanview-therapy.md", __ASTRO_IMAGE_IMPORT_Z1nOAjo], ["./_images/northwind-4x5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fspeech-for-yourself.md", __ASTRO_IMAGE_IMPORT_2dOo6F], ["./_images/post-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwhy-astro-for-agency-sites.mdx", __ASTRO_IMAGE_IMPORT_Z1DgQ04], ["./_images/post-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fdesigning-for-slow-connections.mdx", __ASTRO_IMAGE_IMPORT_jvWQA], ["./_images/post-3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fseo-audits-we-actually-run.mdx", __ASTRO_IMAGE_IMPORT_Z1YgYCL], ["./_images/post-4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Frunning-discovery-workshops.mdx", __ASTRO_IMAGE_IMPORT_1rTpJ6], ["./_images/post-5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpricing-a-small-agency.mdx", __ASTRO_IMAGE_IMPORT_1WFRv7]]);
		