
import __ASTRO_IMAGE_IMPORT_2f42VG from "./_images/elevate-16x9.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Felevate-salon.md";
import __ASTRO_IMAGE_IMPORT_O9gSA from "./_images/elevate-4x5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Felevate-salon.md";
import __ASTRO_IMAGE_IMPORT_Z21gnsa from "./_images/oceanview-16x9.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Foceanview-therapy.md";
import __ASTRO_IMAGE_IMPORT_Z1OKnzM from "./_images/oceanview-4x5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Foceanview-therapy.md";
import __ASTRO_IMAGE_IMPORT_Z1DgQ04 from "./_images/post-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwhy-astro-for-agency-sites.mdx";
import __ASTRO_IMAGE_IMPORT_jvWQA from "./_images/post-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fdesigning-for-slow-connections.mdx";
import __ASTRO_IMAGE_IMPORT_Z1YgYCL from "./_images/post-3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fseo-audits-we-actually-run.mdx";
import __ASTRO_IMAGE_IMPORT_1rTpJ6 from "./_images/post-4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Frunning-discovery-workshops.mdx";
import __ASTRO_IMAGE_IMPORT_1WFRv7 from "./_images/post-5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpricing-a-small-agency.mdx";
import __ASTRO_IMAGE_IMPORT_2ggQdY from "./_images/speech4yourself-16x9.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fspeech-for-yourself.md";
import __ASTRO_IMAGE_IMPORT_Z7pKkC from "./_images/speech4yourself-4x5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fspeech-for-yourself.md";
export default new Map([["./_images/elevate-16x9.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Felevate-salon.md", __ASTRO_IMAGE_IMPORT_2f42VG], ["./_images/elevate-4x5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Felevate-salon.md", __ASTRO_IMAGE_IMPORT_O9gSA], ["./_images/oceanview-16x9.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Foceanview-therapy.md", __ASTRO_IMAGE_IMPORT_Z21gnsa], ["./_images/oceanview-4x5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Foceanview-therapy.md", __ASTRO_IMAGE_IMPORT_Z1OKnzM], ["./_images/post-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwhy-astro-for-agency-sites.mdx", __ASTRO_IMAGE_IMPORT_Z1DgQ04], ["./_images/post-2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fdesigning-for-slow-connections.mdx", __ASTRO_IMAGE_IMPORT_jvWQA], ["./_images/post-3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fseo-audits-we-actually-run.mdx", __ASTRO_IMAGE_IMPORT_Z1YgYCL], ["./_images/post-4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Frunning-discovery-workshops.mdx", __ASTRO_IMAGE_IMPORT_1rTpJ6], ["./_images/post-5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpricing-a-small-agency.mdx", __ASTRO_IMAGE_IMPORT_1WFRv7], ["./_images/speech4yourself-16x9.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fspeech-for-yourself.md", __ASTRO_IMAGE_IMPORT_2ggQdY], ["./_images/speech4yourself-4x5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fspeech-for-yourself.md", __ASTRO_IMAGE_IMPORT_Z7pKkC]]);
		